dja/zap/apps/accounts/urls.py
from django.urls import path
from django.utils.translation import gettext_lazy as _

from . import views

app_name = "accounts"

urlpatterns = [
    path(_("account_summary/"), views.AccountSummary.as_view(), name="account_summary"),
    path(
        _("account_messages/"), views.AccountMessages.as_view(), name="account_messages"
    ),
    path(
        _("account_message/<int:pk>"),
        views.AccountMessage.as_view(),
        name="account_message",
    ),
    path(
        _("account_pref_perso"),
        views.AccountPrefPerso.as_view(),
        name="account_pref_perso",
    ),
    path(
        _("account_pref_socio"),
        views.AccountPrefSocio.as_view(),
        name="account_pref_socio",
    ),
    path(
        _("account_pref_signin"),
        views.AccountPrefSignin.as_view(),
        name="account_pref_signin",
    ),
    path(_("download/<int:pk>"), views.DownloadFile.as_view(), name="download"),
    path(_("project/"), views.ProjectView.as_view(), name="project"),
    path(_("e"), views.EditAddressCpProject.as_view(), name="edit_addresscp"),
]

dja/zap/urls.py
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.sitemaps import views
from django.urls import include, path
from django.utils.translation import gettext_lazy as _
from django.views.generic.base import RedirectView, TemplateView
from zap.apps.base.sitemaps import PostSitemap, RootSitemap

sitemaps = {
    "posts": PostSitemap,
    "root": RootSitemap,
}

# from zap.apps.search.views import SearchProductInventory
urlpatterns = [
    path("tz_detect/", include("tz_detect.urls")),
    path("tinymce/", include("tinymce.urls")),
    path(
        "robots.txt",
        TemplateView.as_view(
            template_name="base/robots.txt", content_type="text/plain"
        ),
    ),
    # path('__debug__/', include('debug_toolbar.urls')),
    path(
        "sitemap.xml",
        views.index,
        {"sitemaps": sitemaps},
        name="django.contrib.sitemaps.views.index",
    ),
    path(
        "sitemap-<section>.xml",
        views.sitemap,
        {"sitemaps": sitemaps},
        name="django.contrib.sitemaps.views.sitemap",
    ),
]
urlpatterns += i18n_patterns(
    path(_("chat/"), include("zap.apps.chat.urls")),
    path("", include("zap.apps.monitor.urls")),
    # path("api/search/<str:query>/", SearchProductInventory.as_view()),
    path("", include("zap.apps.accounts.urls")),
    path("", include("zap.apps.articles.urls")),
    path("", include("zap.apps.base.urls")),
    path("", include("zap.apps.users.urls")),
    path("legal/", include("zap.apps.legal.urls")),
    path("", include("zap.apps.filespro.urls")),
    path("", include("zap.apps.xsys.urls")),
    path("admin/", admin.site.urls),
    # path("account/", include("django.contrib.auth.urls")),
)

if settings.DEBUG and not settings.PROD:
    # urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT_DEV)

dja/zap/apps/accounts/models.py
import datetime
import logging
import os

from django.conf import settings
from django.db import models, transaction
from django.utils import timezone
from django.utils.crypto import get_random_string
from django.utils.translation import gettext_lazy as _

logger = logging.getLogger(__name__)


def uploadPathFunction(instance, filename):
    return os.path.join("HG5GPD8/%s/" % get_random_string(8), filename)


def uploadPathFunctionAvatar(instance, filename):
    return "avatars/%s" % get_random_string(8) + ".png"


STATUS_CHOICES = [
    ("bo", "Booked"),
    ("ca", "Cancelled"),
    ("pr", "In Progress"),
    ("pe", "Pending"),
    ("de", "Delivered"),
    ("pd", "Partially Delivered"),
    ("re", "Refunded"),
    ("pr", "Partially Refunded"),
    ("pi", "Paid"),
    ("pp", "Partially Paid"),
    ("de", "Declined"),
    ("ap", "Awaiting Payment"),
    ("au", "Awaiting Pickup"),
    ("as", "Awaiting Shipment"),
    ("co", "Completed"),
    ("af", "Awaiting Fulfillment"),
    ("mv", "Manual Verification Required"),
    ("di", "Disputed"),
    ("ap", "Approved"),
    ("pa", "Pending approval"),
    ("in", "Incomplete"),
]
ACCOUNTTYPE_CHOICES = [
    ("O", _("Organisation")),
    ("I", _("Individual")),
]

COUNTRY_CHOICES = [
    ("CA", "Canada"),
    ("US", "USA"),
]


class ClientAccount(models.Model):

    account_number = models.CharField(max_length=9, unique=True)
    account_type = models.CharField(
        max_length=1, default="I", choices=ACCOUNTTYPE_CHOICES
    )
    company_name = models.CharField(max_length=35, blank=True)
    company_avatar = models.ImageField(upload_to="avatar", null=True, blank=True)
    is_locked = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    closed_date = models.DateTimeField(blank=True, null=True)
    log = models.TextField(blank=True)

    deposited = models.DecimalField(decimal_places=2, max_digits=10, default=0)
    amount_due = models.DecimalField(decimal_places=2, max_digits=10, default=0)
    invoices = models.ManyToManyField("Invoice", blank=True)
    deposits = models.ManyToManyField("Deposit", blank=True)
    projects = models.ManyToManyField("Project", blank=True)

    def __str__(self):
        return self.account_number

    def add_log(self, text):
        logger.debug(f"Account log: {self.log}")
        self.log += (
            datetime.datetime.now().strftime("%y-%m-%d %H:%M") + " " + text + "\n"
        )
        self.save()

    @classmethod
    def create_client_account(cls):
        # with transaction.atomic():
        param = Param.objects.first()
        new_acc_num = param.last_client_account_number + 1
        param.last_client_account_number = new_acc_num
        param.save()
        s = cls(account_number=str(new_acc_num))
        s.save()
        return s


class Project(models.Model):
    date = models.DateField(default=timezone.now)
    number = models.CharField(max_length=8)
    details = models.CharField(max_length=255)
    status = models.CharField(max_length=2, choices=STATUS_CHOICES, default="pe")

    class Meta:
        ordering = ["-date"]

    def __str__(self):
        return self.number


class Invoice(models.Model):
    date = models.DateField(auto_now_add=True)
    number = models.CharField(max_length=8)
    details = models.CharField(max_length=255)
    invoice_pdf = models.FileField(upload_to=uploadPathFunction)
    project = models.ForeignKey(
        Project, on_delete=models.CASCADE, null=True, blank=True
    )
    status = models.CharField(max_length=30, choices=STATUS_CHOICES, default="green")
    amount = models.DecimalField(decimal_places=2, max_digits=10)

    class Meta:
        ordering = ["-date"]

    def __str__(self):
        return self.number


class Deposit(models.Model):
    date = models.DateField(auto_now_add=True)
    number = models.CharField(max_length=8)
    details = models.CharField(max_length=255)
    receipt_pdf = models.FileField(upload_to=uploadPathFunction)
    invoice = models.ForeignKey(
        Invoice, on_delete=models.CASCADE, null=True, blank=True
    )
    status = models.CharField(max_length=30, choices=STATUS_CHOICES, default="green")
    amount = models.DecimalField(decimal_places=2, max_digits=10)

    class Meta:
        ordering = ["-date"]

    def __str__(self):
        return self.number


class Param(models.Model):
    last_client_account_number = models.IntegerField(default=300000100)


class Mailmessage(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    sender = models.CharField(max_length=12, default="zap")
    subject = models.CharField(max_length=128, blank=True)
    body = models.TextField(blank=True)
    date = models.DateTimeField(default=timezone.now)
    read = models.BooleanField(default=False)
    language = models.CharField(max_length=2, default="en")

    class Meta:
        ordering = ["-date"]


class AddressCp(models.Model):
    name = models.CharField(max_length=40, verbose_name=_("Full Name"))  #
    #   Place additional delivery information such as title, floor, etc. above the civic address.
    add_info = models.CharField(max_length=40, blank=True)
    unit_number = models.CharField(max_length=6, blank=True)  # unit/app. number.
    address_1 = models.CharField(
        max_length=40
    )  #  street address   max chars with unit_number is 40
    city = models.CharField(max_length=30)
    province = models.CharField(max_length=5)
    postal_code = models.CharField(max_length=10)
    country = models.CharField(max_length=2, default="CA", choices=COUNTRY_CHOICES)
    validated = models.BooleanField(default=False)
    verified_date = models.DateTimeField(blank=True, null=True)
    created_at = models.DateTimeField(default=timezone.now)

    def __str__(self):
        address = self.name + "\n"
        if self.country == "CA":
            if self.add_info:
                address += self.add_info + "\n"
            if self.unit_number:
                address += self.unit_number + "-"
            address += self.address_1 + "\n"
            address += self.city + " " + self.province + "  " + self.postal_code + "\n"
        else:
            address += self.address_1 + "\n"
            address += self.city + " " + self.province + "  " + self.postal_code + "\n"
            address += self.get_country_display()

        return address.upper()


class AddressCpUser(AddressCp):
    client_account = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE
    )


class AddressCpProject(AddressCp):
    client_account = models.ForeignKey(ClientAccount, on_delete=models.CASCADE)


class AddressUPS(models.Model):
    client_account = models.ForeignKey(ClientAccount, on_delete=models.CASCADE)
    name = models.CharField(max_length=35)  #
    #  Recipient's street address
    address_1 = models.CharField(max_length=35, blank=True)
    #  UPS  Additional address information (room, floor, apartment).
    address_2 = models.CharField(max_length=35, blank=True)
    #  Additional address information (department)
    address_3 = models.CharField(max_length=35, blank=True)
    city = models.CharField(max_length=30)
    province = models.CharField(max_length=5)
    postal_code = models.CharField(max_length=9)
    country = models.CharField(max_length=2, default="CA", choices=COUNTRY_CHOICES)
    residential = models.BooleanField(default=False)
    validated = models.BooleanField(default=False)
    verified = models.BooleanField(default=False)
    verified_date = models.DateTimeField(blank=True, null=True)
    created_at = models.DateTimeField(default=timezone.now)

    def __str__(self):
        address = self.name + "\n" + self.address_1 + "\n"
        if self.address_2:
            address += self.address_2 + "\n"
        if self.address_3:
            address += self.address_3 + "\n"
        address += self.city + " " + self.province + "  " + self.postal_code + "\n"
        address += self.get_country_display()

        return address.upper()


class PhoneNumbers(models.Model):

    description = models.CharField(max_length=255)
    phone_number = models.CharField(max_length=255, unique=True)
    is_verified = models.BooleanField(default=False)

dja/zap/apps/accounts/forms.py
from django.core.exceptions import ValidationError
from django.forms import ModelForm

from .models import AddressCpProject, Project


class ProjectForm(ModelForm):
    class Meta:
        model = Project
        fields = "__all__"


class AddressCpForm(ModelForm):
    def clean(self):
        cleaned_data = super().clean()
        unit_number = cleaned_data.get("unit_number")
        address_1 = cleaned_data.get("address_1")
        if unit_number and address_1 and (len(unit_number) + len(address_1) > 40):
            raise ValidationError(
                _(
                    "Unit number and Street address together must total less than %(value)s characters."
                ),
                # _("Unit number and Street address together must total less than %(value)s characters."),
                code="invalid",
                params={"value": "40"},
            )


class AddressCpProjectForm(AddressCpForm):
    class Meta:
        model = AddressCpProject
        exclude = []

dja/zap/apps/accounts/views.py
import logging

from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.paginator import EmptyPage, Paginator
from django.http import FileResponse, HttpResponseRedirect
from django.shortcuts import redirect, render
from django.urls import reverse
from django.utils import timezone
from django.views import View
from zap.apps.users.mixins import LoginRequiredMixinLev2User

from .forms import AddressCpProjectForm, ProjectForm

logger = logging.getLogger(__name__)


class DownloadFile(LoginRequiredMixin, View):
    def get(self, request, pk):
        try:
            path = request.user.client_account.invoices.get(pk=pk).invoice_pdr.path
            response = FileResponse(open(path, "rb"), as_attachment=True)
        except Exception as e:
            logger.error(f"error: DownloadFile: {e}")
        # filename = 'name123.pdf'
        # response = FileResponse(
        # open(path, 'rb'), as_attachment=True, filename=filename)
        return response


class ProjectView(View):
    def get(self, request):
        return self.this_render(request)

    def post(self, request):
        return self.this_render(request)

    def this_render(self, request):
        ctx = {"form": ProjectForm()}
        return render(request, "accounts/register.html", ctx)


class AccountSummary(LoginRequiredMixinLev2User, View):
    def get(self, request):

        return self.this_render(request)

    def post(self, request):
        return self.this_render(request)

    def this_render(self, request):
        user = request.user
        try:
            account = user.client_account
            invoices = account.invoices.all()
            ctx = {"user": user, "account": account, "invoices": invoices}
            return render(request, "accounts/account_summary.html", ctx)
        except Exception as e:
            logger.error(f"error: AccountSummary: {e}")
            return redirect("base:home")


class AccountMessages(LoginRequiredMixin, View):
    def get(self, request):
        user = request.user
        mailmessages = user.mailmessage_set.all()
        p = Paginator(mailmessages, 4, 2)
        page_num = request.GET.get("page", 1)
        try:
            page = p.page(page_num)
        except EmptyPage:
            page = p.page(1)
        ctx = {"email": user.email, "page": page}
        return render(request, "accounts/account_messages.html", ctx)


class AccountMessage(LoginRequiredMixin, View):
    def get(self, request, pk):
        user = request.user
        mailmessage = user.mailmessage_set.get(pk=pk)
        mailmessage.read = True
        mailmessage.save()
        ctx = {"email": user.email, "mailmessage": mailmessage}
        return render(request, "accounts/account_message.html", ctx)


class AccountPrefPerso(LoginRequiredMixin, View):
    def get(self, request):
        return self.this_render(request)

    def post(self, request):
        return self.this_render(request)

    def this_render(self, request):
        user = request.user
        account = user.client_account
        invoices = account.invoices.all()
        ctx = {"email": user.email, "account": account, "invoices": invoices}
        return render(request, "accounts/account_pref_perso.html", ctx)


class AccountPrefSocio(LoginRequiredMixin, View):
    def get(self, request):
        return self.this_render(request)

    def post(self, request):
        return self.this_render(request)

    def this_render(self, request):
        user = request.user
        account = user.client_account
        invoices = account.invoices.all()
        ctx = {"email": user.email, "account": account, "invoices": invoices}
        return render(request, "accounts/account_pref_socio.html", ctx)


class AccountPrefSignin(LoginRequiredMixin, View):
    def get(self, request):
        return self.this_render(request)

    def post(self, request):
        return self.this_render(request)

    def this_render(self, request):
        user = request.user
        account = user.client_account
        invoices = account.invoices.all()
        ctx = {"email": user.email, "account": account, "invoices": invoices}
        return render(request, "accounts/account_pref_signin.html", ctx)


class EditAddressCpProject(View):

    form = AddressCpProjectForm()

    def get(self, request):
        address = request.user.client_account.addresscpproject_set.first()
        if address:
            self.form = AddressCpProjectForm(instance=address)
        return self.this_render(request)

    def post(self, request):
        self.form = AddressCpProjectForm(request.POST)
        if self.form.is_valid():
            # process the data in form.cleaned_data as required
            return HttpResponseRedirect(reverse("base:home"))
        return self.this_render(request)

    def this_render(self, request):
        ctx = {
            "form": self.form,
        }
        return render(request, "accounts/edit_address_cp.html", ctx)

dja/templates/accounts/account__nav-0.html
{% load i18n %}
<main class="mainHFull">
  <section class="account_section" id="account_section">
    <div class="container-fluid">
      <div class="row account_row ps-1 pe-1 text_color">
        <div class="d-flex flex-wrap justify-content-between align-items-center account_nav_text">
          <span class="pe-3 header-1">{% trans "My account" %}</span>
          <span class="link_1 d-flex flex-nowrap align-items-baseline mt-1">
            <a class="link_1 medium_1" href="#">{{user.email}}</a>
            <span class="ps-2 me-1" style="padding-top:6px;">
              <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" fill="currentColor" class="bi bi-bookmark"
                viewBox="0 0 16 16">
                <path
                  d="M2 2a2 2 0 0 1 2-2h8a2 2 0 0 1 2 2v13.5a.5.5 0 0 1-.777.416L8 13.101l-5.223 2.815A.5.5 0 0 1 2 15.5V2zm2-1a1 1 0 0 0-1 1v12.566l4.723-2.482a.5.5 0 0 1 .554 0L13 14.566V2a1 1 0 0 0-1-1H4z" />
              </svg>
            </span>
          </span>
        </div>
        <div class="d-flex flex-wrap justify-content-start align-items-center p-0 m-0">
          {%if actualPage == 'Summary'%}
          <button class="account_btn_menu account_btn_menu__current" disabled {%else%} <button class="account_btn_menu"
            {%endif%} type="button"
            onclick="window.location.href='{% url 'accounts:account_summary' %}'">{% trans "Summary" %}</button>

          {%if actualPage == 'Messages'%}
          <button class="account_btn_menu account_btn_menu__current" disabled {%else%} <button class="account_btn_menu"
            {%endif%} type="button"
            onclick="window.location.href='{% url 'accounts:account_messages' %}'">{% trans "Messages" %}</button>

          {%if actualPage == 'Preferences'%}
          <button class="account_btn_menu account_btn_menu__current" disabled {%else%} <button class="account_btn_menu"
            {%endif%} type="button"
            onclick="window.location.href='{% url 'accounts:account_pref_perso' %}'">{% trans "Preferences" %}</button>
        </div>
        <div class="horizontal_separator_full" style="margin-top:0rem;margin-bottom:0.5rem;"></div>

dja/templates/accounts/account__nav-1.html
</div>
</div>
</section>
{% include 'base/footers/footer_small.html' %}

</main>

dja/templates/accounts/account__nav_pref.html
{% load i18n %}
<div class="p-2 pt-3 pb-1">
  {%if actualPage == 'Perso'%}
  <a class="link_1 m-2" style="font-weight:bold; pointer-events: none;" {%else%} <a class="link_1 m-2" {%endif%}
    href='{% url 'accounts:account_pref_perso' %}'>{% trans "Personal&nbsp;info" %}</a>

  {%if actualPage == 'Socio'%}
  <a class="link_1 m-2" style="font-weight:bold; pointer-events: none;" {%else%} <a class="link_1 m-2" {%endif%}
    href='{% url 'accounts:account_pref_socio' %}'>{% trans "Social&nbsp;info" %}</a>

  {%if actualPage == 'Signin'%}
  <a class="link_1 m-2" style="font-weight:bold; pointer-events: none;" {%else%} <a class="link_1 m-2" {%endif%}
    href='{% url 'accounts:account_pref_signin' %}'>{% trans "Sign&#8209;in&nbsp;and&nbsp;security" %}</a>
</div>

dja/templates/accounts/account_message.html
{% extends 'main.html' %}
{% load i18n %} {% load l10n %} {% load tz %}
{% block title %}{% trans "Message" %}{% endblock %}
{% block desc %}{% trans "" %}{% endblock %}
{% block content %}
{% include "accounts/account__nav-0.html" with actualPage="Messages" %}
<div class="p-2 pt-3 pb-1 d-flex justify-content-between align-items-baseline">
  <span class="fs-5">{% trans "Message content" %}</span>
  <div>
    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-arrow-left"
      viewBox="0 0 16 16">
      <path fill-rule="evenodd"
        d="M15 8a.5.5 0 0 0-.5-.5H2.707l3.147-3.146a.5.5 0 1 0-.708-.708l-4 4a.5.5 0 0 0 0 .708l4 4a.5.5 0 0 0 .708-.708L2.707 8.5H14.5A.5.5 0 0 0 15 8z" />
    </svg>
    <a class="link_1" href="{% url 'accounts:account_messages' %}">{% trans "Back to messages" %}</a>
  </div>
</div>
<div class="account_message_div mt-1 pt-3 pb-3">
  <p class="fs-5">{{ mailmessage.subject }}</p>
  <p>
    <div>{% trans "From:" %} {{ mailmessage.sender }}</div>
    <div>{% trans "Sent:" %} {{ mailmessage.date|localtime|localize }}</div>
  </p>
  <div class="horizontal_separator_full" style="margin-top:0rem;margin-bottom:1.5rem;"></div>
  <div>
    {{ mailmessage.body }}
  </div>
</div>
{% include "accounts/account__nav-1.html" %}
{% endblock %}

dja/templates/accounts/account_messages.html
{% extends 'main.html' %}
{% load i18n %}
{% block title %}{% trans "Messages" %}{% endblock %}
{% block desc %}{% trans "" %}{% endblock %}
{% block content %}
{% include "accounts/account__nav-0.html" with actualPage="Messages" %}
<div class="p-2 pt-3 pb-1 d-flex justify-content-between align-items-baseline">
  <span class="header-2">{% trans "Messages" %}</span>
  <nav aria-label="Page navigation">
    <ul class="pagination m-0">
      {% if page.has_previous %}
      <li class="page-item"><a class="page-link"
          href="{% url 'accounts:account_messages' %}?page={{page.previous_page_number}}">&#60;</a></li>
      {%endif%}
      {% if page.paginator.num_pages > 1 %}
      <li class="page-item"><a class="page-link" style="min-width:80px; pointer-events: none;" href="#">p.
          {{page.number}} of {{ page.paginator.num_pages }}</a></li>
      {%endif%}
      {% if page.has_next %}
      <li class="page-item"><a class="page-link"
          href="{% url 'accounts:account_messages' %}?page={{page.next_page_number}}">&#62;</a></li>
      {%endif%}
    </ul>
  </nav>
</div>
<table class="table table-hover account_tab_message">
  <tr>
    <th scope="col" style="width:100px">{% trans "From" %}</th>
    <th scope="col" style="width:450px">{% trans "Subject" %}</th>
    <th scope="col" style="width:120px">{% trans "Received" %}</th>
  </tr>
  {% for i in page %}
  <tr class="entireTableRowIsLink" data-href="{% url 'accounts:account_message' i.id %}"
    {% if not i.read %}style="font-weight:bold" {%endif%}>
    <td scope="col">{{i.sender}}</td>
    <td scope="col">{{i.subject}}</td>
    <td scope="col">{{ i.date | date:'d M Y'}}</td>
  </tr>
  {% endfor %}
</table>
{% include "accounts/account__nav-1.html" %}
{% endblock %}

dja/templates/accounts/account_pref_signin.html
{% extends 'main.html' %}
{% load i18n %}
{% block title %}{% trans "Pref. Sign-in" %}{% endblock %}
{% block desc %}{% trans "" %}{% endblock %}
{% block content %}
{% include "accounts/account__nav-0.html" with actualPage="Preferences" %}
{% include "accounts/account__nav_pref.html" with actualPage="Signin" %}
<!-- /////////////////////////////////////////////////////////////////////////////////////////////////
                                Sign-in and security
/////////////////////////////////////////////////////////////////////////////////////////////////////-->
<div class="p-0 ps-2">
  <div class="d-flex flex-wrap justify-content-between align-items-baseline">
    <div class="p-2 pt-4 pb-1 fs-5">
      {% trans "Sign-in and security" %}
    </div>
    <div class="d-flex flex-nowrap">
      <button type="button" class="rounded-pill btn-login btn-login__help ms-2 me-1"
        style="width:80px; height:40px;">{% trans "Cancel" %}</button>
      <button type="button" class="rounded-pill btn-login btn-login__texto__on"
        style="width:80px; height:40px;">{% trans "Save" %}</button>
    </div>

  </div>
  <div class="horizontal_separator_full color_tame" style="margin-top:1rem;margin-bottom:0.5rem;"></div>
  <!-- //////////////////////////////////////////////////////////////////////////////
                                        Change password
        ///////////////////////////////////////////////////////////////////////////////////-->
  <div class="row account_preference_row p-2">
    <div class="p-2 col-12 col-md-5">
      <strong>{% trans "Change password" %}</strong>
    </div>
    <div class="p-2 col-12 col-md-7">
      <!-- Entry -->
      <div>
        {% trans "Actual password" %}
      </div>
      <div class="text-black pb-3">
        <div class="form-floating">
          <input type="text" class="form-control login_inp-error" style="max-width:300px;" id="inputActualPassword"
            placeholder="Actual password">
          <label for="inputActualPassword">{% trans "Actual password" %}</label>
        </div>
        <label class="account_validate-label">{% trans "Please enter your actual password." %}</label>
      </div>
      <!-- Entry -->
      <div>
        {% trans "New password" %}
      </div>
      <div class="text-black pb-3">
        <div class="form-floating">
          <input type="text" class="form-control login_inp-error" style="max-width:300px;" id="inputNewPassword"
            placeholder="New password">
          <label for="inputNewPassword">{% trans "New password" %}</label>
        </div>
        <label class="account_validate-label">{% trans "Please enter your new password." %}</label>
      </div>
      <!-- Entry -->
      <div>
        {% trans "New password (repeat)" %}
      </div>
      <div class="text-black pb-3">
        <div class="form-floating">
          <input type="text" class="form-control login_inp-error" style="max-width:300px;" id="inputNewPassword2"
            placeholder="New password (repeat)">
          <label for="inputNewPassword2">{% trans "New password (repeat)" %}</label>
        </div>
        <label class="account_validate-label">{% trans "Please enter your new password (repeat)." %}</label>
      </div>
    </div>
  </div>
  <div class="horizontal_separator_full color_tame" style="margin-top:1rem;margin-bottom:1rem;"></div>
  <!-- //////////////////////////////////////////////////////////////////////////////
                                        Keep me signed in
        ///////////////////////////////////////////////////////////////////////////////////-->
  <div class="row account_preference_row p-2">
    <div class="p-2 col-12 col-md-5">
      <strong>{% trans "Sign-in preferences" %}</strong>
    </div>
    <div class="p-2 col-12 col-md-7">
      <div class="form-check">
        <label class="form-check-label">
          {% trans "Keep me signed-in on this device." %}
          <input class="form-check-input" type="checkbox" value="" checked>
        </label>
      </div>
    </div>
  </div>
  <div class="horizontal_separator_full color_tame" style="margin-top:1rem;margin-bottom:1rem;"></div>
  <!-- //////////////////////////////////////////////////////////////////////////////
                                        Close account
        ///////////////////////////////////////////////////////////////////////////////////-->
  <div class="row account_preference_row p-2">
    <div class="p-2 col-12 col-md-5">
      <strong>{% trans "Close my account" %}</strong>
    </div>
    <div class="p-2 col-12 col-md-7">
      <button type="button" class="rounded-pill btn-login btn-login__help ms-2 me-1"
        style="width:150px; height:40px;">{% trans "Close my account" %}</button>
    </div>
  </div>
  <div class="horizontal_separator_full color_tame" style="margin-top:1rem;margin-bottom:1rem;"></div>
</div>
{% include "accounts/account__nav-1.html" %}
{% endblock %}