dja/zap/apps/monitor/urls.py
from django.urls import path
from django.utils.translation import gettext_lazy as _

from . import views

app_name = "monitor"

urlpatterns = [
    path(_("monitor625453245/"), views.StaffMonitor.as_view(), name="monitor"),
    path(
        "MyAjaxReceiveTestView/",
        views.MyAjaxReceiveTestView.as_view(),
        name="MyAjaxReceiveTestView",
    ),
    path(
        "MonitorScript/",
        views.MonitorScript.as_view(),
        name="MonitorScript",
    ),
]

dja/zap/urls.py
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.sitemaps import views
from django.urls import include, path
from django.utils.translation import gettext_lazy as _
from django.views.generic.base import RedirectView, TemplateView
from zap.apps.base.sitemaps import PostSitemap, RootSitemap

sitemaps = {
    "posts": PostSitemap,
    "root": RootSitemap,
}

# from zap.apps.search.views import SearchProductInventory
urlpatterns = [
    path("tz_detect/", include("tz_detect.urls")),
    path("tinymce/", include("tinymce.urls")),
    path(
        "robots.txt",
        TemplateView.as_view(
            template_name="base/robots.txt", content_type="text/plain"
        ),
    ),
    # path('__debug__/', include('debug_toolbar.urls')),
    path(
        "sitemap.xml",
        views.index,
        {"sitemaps": sitemaps},
        name="django.contrib.sitemaps.views.index",
    ),
    path(
        "sitemap-<section>.xml",
        views.sitemap,
        {"sitemaps": sitemaps},
        name="django.contrib.sitemaps.views.sitemap",
    ),
]
urlpatterns += i18n_patterns(
    path(_("chat/"), include("zap.apps.chat.urls")),
    path("", include("zap.apps.monitor.urls")),
    # path("api/search/<str:query>/", SearchProductInventory.as_view()),
    path("", include("zap.apps.accounts.urls")),
    path("", include("zap.apps.articles.urls")),
    path("", include("zap.apps.base.urls")),
    path("", include("zap.apps.users.urls")),
    path("legal/", include("zap.apps.legal.urls")),
    path("", include("zap.apps.filespro.urls")),
    path("", include("zap.apps.xsys.urls")),
    path("admin/", admin.site.urls),
    # path("account/", include("django.contrib.auth.urls")),
)

if settings.DEBUG and not settings.PROD:
    # urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT_DEV)

dja/zap/apps/monitor/models.py
from django.db import models

dja/zap/apps/monitor/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.utils.translation import gettext_lazy as _

UserModel = get_user_model()


class EmailAddressForm(forms.Form):
    email = forms.EmailField()

dja/zap/apps/monitor/views.py
# chat/views.py
import logging
import os
from datetime import datetime

from django.contrib.auth import get_user_model
from django.contrib.contenttypes.models import ContentType
from django.http import HttpResponse, JsonResponse
from django.shortcuts import redirect, render
from django.utils.decorators import method_decorator
from django.utils.translation import gettext_lazy as _
from django.views import View
from django.views.decorators.csrf import csrf_protect
from django.views.decorators.http import require_POST

logger = logging.getLogger(__name__)

UserModel = get_user_model()

from zap.apps.users.mixins import LoginRequiredMixinLev2Superuser


class StaffMonitor(LoginRequiredMixinLev2Superuser, View):
    def get(self, request):

        return self.this_render(request)

    def post(self, request):
        return self.this_render(request)

    def this_render(self, request):
        try:
            ctx = {
                "my_object_list": ["apple", "banana", "cherry"],
            }
            return render(request, "monitor/monitor.html", ctx)
        except Exception as e:
            logger.error(f"error: StaffMonitor: {e}")
            return redirect("base:home")


class MonitorScript(View):
    def get(self, request):
        if request.user.is_superuser:
            response = HttpResponse()
            response["X-Accel-Redirect"] = "/media_private/js/priv_monitor_script.js"
            return response


@method_decorator(csrf_protect, name="dispatch")
@method_decorator(require_POST, name="dispatch")
class MyAjaxReceiveTestView(View):
    def post(self, request, *args, **kwargs):
        # Ensure the request is AJAX
        if not is_ajax(request):
            return JsonResponse({"error": "Invalid request"}, status=400)

        # Get the message from the POST data
        message = request.POST.get("message")

        # Do something with the message...
        logger.debug(f"AJAX Received message: {message}")

        # Send back a JSON response
        return JsonResponse(
            {
                "original_message": message,
                "response_message": "This is a response from Django",
            }
        )


def is_ajax(request):
    return request.headers.get("x-requested-with") == "XMLHttpRequest"

dja/templates/monitor/monitor.html
{% extends 'main.html' %}
{% load i18n %} {% load static %}
{% block title %}{% trans "Monitor" %}{% endblock %}
{% block desc %}{% trans "" %}{% endblock %}
{% block content %}

<main class="mainHFull">
  <section class="home_section">
    <div class="h-100 d-flex gap-2">
      <div class="d-flex flex-column flex-grow-1 gap-1" style="min-width:300px;">
        <textarea class="command-log" id="command-log"></textarea>
        <textarea class="command-input" id="command-input" spellcheck="false" type="text" rows="2"></textarea>
        <button class="command-submit" id="command-submit">{% trans "Send command" %}</button>
      </div>

      <div class="m-0 p-0 d-flex flex-column align-items-start" style="min-width:250px;">
        Shared files
        <div class="fileUploadCtn">
          <div class="fileUploadList">

          </div>
          <input class="fileUploadRealInput" type="file" hidden="hidden">
          <button class="fileUploadChooseBtn">{% trans "Choose a file from my computer" %}</button>
          <div class="fileUploadChoiceTxt"></div>
          <button class="fileUploadSendBtn">{% trans "Send the file on the server" %}</button>
          <button class="fileUploadCancelBtn">{% trans "Cancel" %}</button>
          <div class="fileUploadLogTxt"></div>
        </div>

        Test
      </div>

      <div class="d-flex flex-column align-items-start" style="width:250px;">
        Typesense
        <button class='monitorSendCommand'>movies_fixture_to_db</button>
        <button class='monitorSendCommand'>delete_all_movies_from_db</button>
        <button class='monitorSendCommand'>typesense_delete_a_collection</button>
        <button class='monitorSendCommand'>typesense_create_a_collection</button>
        <button class='monitorSendCommand'>typesense_import_documents</button>
        <button class='monitorSendCommand'>typesense_test_count_documents</button>
        <button class='monitorSendCommand'>typesense_add_single_document</button>
        Websocket tests
        <label> Packet size<input type="text" value="1024" id="wstestsize" style="width:100px;"></label>
        <label> Repetitions<input type="text" value="5" id="wstestrepetitions" style="width:100px;"></label>
        <label> Delay ms<input type="text" value="500" id="wstestdelay" style="width:100px;"></label>
        <button class='monitorFunction'>sendPacketBurstJS</button>
        <button class='monitorFunction'>connectAndDisconnectJS</button>
        <button class='monitorSendCommand'>close_connection_in_django</button>
        <button class='monitorFunction'>sendBinaryMessage</button>
        Ajax tests
        <button class='monitorFunction'>showMyObjectList</button>
        <button class='monitorFunction'>sendAjaxRequest</button>

      </div>
    </div>
  </section>

</main>

{{ my_object_list|json_script:'myObjectList' }}
{% url 'monitor:MyAjaxReceiveTestView' as my_url_send_request %}
{{ my_url_send_request|json_script:"myURLsendRequest" }}

<script src="{% url 'monitor:MonitorScript' %}"></script>

<style>
  .command-log {
    width: 100%;
    height: 100%;
    resize: none;
    background: var(--color-cmd-bg);
    color: var(--color-text);
  }

  .command-input {
    width: 100%;
    resize: none;
    background: var(--color-cmd-bg);
    color: var(--color-text);
  }

  .command-submit {
    width: 100%;
    resize: none;
    background: var(--color-cmd-bg);
    color: var(--color-text);
  }

  label {
    font-weight: bold;
  }
</style>

{% endblock %}