dja/zap/apps/legal/urls.py
from django.urls import path
from django.utils.translation import gettext_lazy as _

from . import views

app_name = "legal"

urlpatterns = [
    path(_("terms-of-service"), views.terms_of_service, name="terms_of_service"),
    path(_("privacy-policy"), views.privacy_policy, name="privacy_policy"),
    path(_("cookie-policy"), views.cookie_policy, name="cookie_policy"),
    path(_("acceptable-use-policy"), views.acceptable_use_policy, name="acceptable_use_policy"),
    path(_("return-and-refund-policy"), views.return_and_refund_policy, name="return_and_refund_policy"),
    path(_(""), views.terms_of_service, name="terms_of_service"),
]

dja/zap/urls.py
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.sitemaps import views
from django.urls import include, path
from django.utils.translation import gettext_lazy as _
from django.views.generic.base import RedirectView, TemplateView
from zap.apps.base.sitemaps import PostSitemap, RootSitemap

sitemaps = {
    "posts": PostSitemap,
    "root": RootSitemap,
}

# from zap.apps.search.views import SearchProductInventory
urlpatterns = [
    path("tz_detect/", include("tz_detect.urls")),
    path("tinymce/", include("tinymce.urls")),
    path(
        "robots.txt",
        TemplateView.as_view(
            template_name="base/robots.txt", content_type="text/plain"
        ),
    ),
    # path('__debug__/', include('debug_toolbar.urls')),
    path(
        "sitemap.xml",
        views.index,
        {"sitemaps": sitemaps},
        name="django.contrib.sitemaps.views.index",
    ),
    path(
        "sitemap-<section>.xml",
        views.sitemap,
        {"sitemaps": sitemaps},
        name="django.contrib.sitemaps.views.sitemap",
    ),
]
urlpatterns += i18n_patterns(
    path(_("chat/"), include("zap.apps.chat.urls")),
    path("", include("zap.apps.monitor.urls")),
    # path("api/search/<str:query>/", SearchProductInventory.as_view()),
    path("", include("zap.apps.accounts.urls")),
    path("", include("zap.apps.articles.urls")),
    path("", include("zap.apps.base.urls")),
    path("", include("zap.apps.users.urls")),
    path("legal/", include("zap.apps.legal.urls")),
    path("", include("zap.apps.filespro.urls")),
    path("", include("zap.apps.xsys.urls")),
    path("admin/", admin.site.urls),
    # path("account/", include("django.contrib.auth.urls")),
)

if settings.DEBUG and not settings.PROD:
    # urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT_DEV)

dja/zap/apps/legal/views.py
from django.shortcuts import render
from django.utils.translation import gettext_lazy as _


def terms_of_service(request):
    return render(request, "legal/terms_of_service.html", {})


def privacy_policy(request):
    return render(request, "legal/privacy_policy.html", {})


def cookie_policy(request):
    return render(request, "legal/cookie_policy.html", {})


def acceptable_use_policy(request):
    return render(request, "legal/acceptable_use_policy.html", {})


def return_and_refund_policy(request):
    return render(request, "legal/return_and_refund_policy.html", {})

dja/templates/legal/acceptable_use_policy.html
{% extends 'main.html' %}
{% load i18n %}
{% block title %}{% trans "Acceptable Use Policy" %}{% endblock %}
{% block desc %}{% trans "" %}{% endblock %}
{% get_current_language as CURRENT_LANGUAGE %}
{% block content %}

{% include "legal/legal__nav-0.html" with actualPage="AUP" %}
{% if CURRENT_LANGUAGE == "en" %}
Fugiat sunt cupidatat adipisicing enim magna Lorem. Cupidatat veniam eu fugiat eu irure proident culpa.
Tempor
mollit in anim culpa. Non Lorem ea minim id elit ad.
{% endif %}
{% if CURRENT_LANGUAGE == "fr" %}
Fugiat sunt cupidatat adipisicing enim magna Lorem. Cupidatat veniam eu fugiat eu irure proident culpa.
Tempor
mollit in anim culpa. Non Lorem ea minim id elit ad.
{% endif %}
{% include "legal/legal__nav-1.html" %}

{% endblock %}

dja/templates/legal/cookie_policy.html
{% extends 'main.html' %}
{% load i18n %}
{% block title %}{% trans "Cookie Policy" %}{% endblock %}
{% block desc %}{% trans "" %}{% endblock %}
{% get_current_language as CURRENT_LANGUAGE %}
{% block content %}

{% include "legal/legal__nav-0.html" with actualPage="CP" %}
{% if CURRENT_LANGUAGE == "en" %}
Fugiat sunt cupidatat adipisicing enim magna Lorem. Cupidatat veniam eu fugiat eu irure proident culpa.
Tempor

mollit in anim culpa. Non Lorem ea minim id elit ad.
<p id="cookieDetails">
    Cookie details
    ...
</p>
{% endif %}
{% if CURRENT_LANGUAGE == "fr" %}
Fugiat sunt cupidatat adipisicing enim magna Lorem. Cupidatat veniam eu fugiat eu irure proident culpa.
Tempor
mollit in anim culpa. Non Lorem ea minim id elit ad.
<p id="cookieDetails">
    Cookie details
    ...
</p>
{% endif %}
{% include "legal/legal__nav-1.html" %}

{% endblock %}

dja/templates/legal/legal__nav-0.html
{% load i18n %}
<main class="d-flex flex-fill">
  <section id="legal_section" class="legal_section">
    <div class="container-fluid">
      <div class="row justify-content-center legal_row">
        <div class="d-flex flex-wrap">
          <div class="col-12 col-lg-3 col-md-auto">
            <div class="legal_nav legal-font--small">
              <ul class="list-inline">
                <li><a class="text-{%if actualPage == 'TOS'%}select{%else%}normal{%endif%}" href="
                  {% url 'legal:terms_of_service' %}">{% trans "Terms of Service" %}</a></li>
                <li><a class="text-{%if actualPage == 'PP'%}select{%else%}normal{%endif%}" href="
                  {% url 'legal:privacy_policy' %}">{% trans "Privacy Policy" %}</a></li>
                <li><a class="text-{%if actualPage == 'CP'%}select{%else%}normal{%endif%}" href="
                  {% url 'legal:cookie_policy' %}">{% trans "Cookie Policy" %}</a></li>
                <li><a class="text-{%if actualPage == 'AUP'%}select{%else%}normal{%endif%}" href="
                  {% url 'legal:acceptable_use_policy' %}">{% trans "Acceptable Use Policy" %}</a></li>
                <li><a class="text-{%if actualPage == 'RRP'%}select{%else%}normal{%endif%}" href="
                  {% url 'legal:return_and_refund_policy' %}">{% trans "Return and Refund Policy" %}</a></li>
              </ul>
            </div>
          </div>
          <span class="col-12 col-lg-9 col-md">
            <div class="legal_doc legal-font">

dja/templates/legal/legal__nav-1.html
</div>
</div>
</div>
</div>
</div>
</section>
</main>

{% include 'base/footers/footer_small.html' %}

dja/templates/legal/privacy_policy.html
{% extends 'main.html' %}
{% load i18n %}
{% block title %}{% trans "Privacy Policy" %}{% endblock %}
{% block desc %}{% trans "" %}{% endblock %}
{% get_current_language as CURRENT_LANGUAGE %}
{% block content %}

{% include "legal/legal__nav-0.html" with actualPage="PP" %}
{% if CURRENT_LANGUAGE == "en" %}
<p class="legal-font--title-1">
  Zap, inc. Privacy Policy
</p>
<p class="legal-font--small">
  Updated: 25 November, 2022
</p>
<p class="legal-font--title-2">
  About Zap
</p>
<p>

  The user's timezone is being detected with JavaScript and stored in the user's session. The timezone information is
  derived from the user's system settings, not their physical location.


  Non incididunt eiusmod elit occaecat. Aliquip ex dolore velit mollit occaecat eu velit cupidatat esse
  ipsum
  culpa sint. Laborum mollit minim proident nulla proident anim et exercitation. Cupidatat enim do sint
  incididunt aliquip mollit. Irure sint irure adipisicing consectetur id duis sint labore do magna commodo
  nisi
  est.Dolore ea occaecat nulla fugiat cillum aute enim officia aliquip dolore non magna elit. Sint deserunt
  commodo culpa pariatur qui anim irure adipisicing commodo ea. Eiusmod est amet do ex cillum in mollit est
</p>
<p>WE DO NOT AND WILL NOT SELL YOUR PERSONAL INFORMATION.</p>
<p>
  <table class="table">
    <thead>
      <tr>
        <th class="col-4">Last</th>
        <th class="col-8">Handle</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td rowspan="2">Otto</td>
        <td>@mdo</td>
      </tr>
      <tr>
        <td>@fat</td>
      </tr>
      <tr>
        <td>the Bird</td>
        <td>@twitter</td>
      </tr>
    </tbody>
  </table>
</p>
{% endif %}
{% if CURRENT_LANGUAGE == "fr" %}
Fugiat sunt cupidatat adipisicing enim magna Lorem. Cupidatat veniam eu fugiat eu irure proident culpa.
Tempor
mollit in anim culpa. Non Lorem ea minim id elit ad.
{% endif %}
{% include "legal/legal__nav-1.html" %}

{% endblock %}

dja/templates/legal/return_and_refund_policy.html
{% extends 'main.html' %}
{% load i18n %}
{% block title %}{% trans "Return and Refund Policy" %}{% endblock %}
{% block desc %}{% trans "" %}{% endblock %}
{% get_current_language as CURRENT_LANGUAGE %}
{% block content %}

{% include "legal/legal__nav-0.html" with actualPage="RRP" %}
{% if CURRENT_LANGUAGE == "en" %}
Fugiat sunt cupidatat adipisicing enim magna Lorem. Cupidatat veniam eu fugiat eu irure proident culpa.
{% endif %}
{% if CURRENT_LANGUAGE == "fr" %}
Fugiat sunt cupidatat adipisicing enim magna Lorem. Cupidatat veniam eu fugiat eu irure proident culpa.
{% endif %}
{% include "legal/legal__nav-1.html" %}

{% endblock %}

dja/templates/legal/terms_of_service.html
{% extends 'main.html' %}
{% load i18n %}
{% block title %}{% trans "Terms of service" %}{% endblock %}
{% block desc %}{% trans "" %}{% endblock %}
{% get_current_language as CURRENT_LANGUAGE %}
{% block content %}

{% include "legal/legal__nav-0.html" with actualPage="TOS" %}
{% if CURRENT_LANGUAGE == "en" %}
Fugiat sunt cupidatat adipisicing enim magna Lorem. Cupidatat veniam eu fugiat eu irure proident culpa.
{% endif %}
{% if CURRENT_LANGUAGE == "fr" %}
Fugiat sunt cupidatat adipisicing enim magna Lorem. Cupidatat veniam eu fugiat eu irure proident culpa.
{% endif %}
{% include "legal/legal__nav-1.html" %}

{% endblock %}