dja/zap/apps/articles/urls.py
from django.urls import path
from django.utils.translation import gettext_lazy as _

from . import views

app_name = "articles"

urlpatterns = [
    path(_("articles/"), views.ListOfArticles.as_view(), name="articles"),
    path(_("article/<slug:article_slug>/"), views.ArticlePage.as_view(), name="article"),
    path(_("author/<slug:author_slug>/"), views.AuthorPage.as_view(), name="author"),
]

dja/zap/urls.py
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.sitemaps import views
from django.urls import include, path
from django.utils.translation import gettext_lazy as _
from django.views.generic.base import RedirectView, TemplateView
from zap.apps.base.sitemaps import PostSitemap, RootSitemap

sitemaps = {
    "posts": PostSitemap,
    "root": RootSitemap,
}

# from zap.apps.search.views import SearchProductInventory
urlpatterns = [
    path("tz_detect/", include("tz_detect.urls")),
    path("tinymce/", include("tinymce.urls")),
    path(
        "robots.txt",
        TemplateView.as_view(
            template_name="base/robots.txt", content_type="text/plain"
        ),
    ),
    # path('__debug__/', include('debug_toolbar.urls')),
    path(
        "sitemap.xml",
        views.index,
        {"sitemaps": sitemaps},
        name="django.contrib.sitemaps.views.index",
    ),
    path(
        "sitemap-<section>.xml",
        views.sitemap,
        {"sitemaps": sitemaps},
        name="django.contrib.sitemaps.views.sitemap",
    ),
]
urlpatterns += i18n_patterns(
    path(_("chat/"), include("zap.apps.chat.urls")),
    path("", include("zap.apps.monitor.urls")),
    # path("api/search/<str:query>/", SearchProductInventory.as_view()),
    path("", include("zap.apps.accounts.urls")),
    path("", include("zap.apps.articles.urls")),
    path("", include("zap.apps.base.urls")),
    path("", include("zap.apps.users.urls")),
    path("legal/", include("zap.apps.legal.urls")),
    path("", include("zap.apps.filespro.urls")),
    path("", include("zap.apps.xsys.urls")),
    path("admin/", admin.site.urls),
    # path("account/", include("django.contrib.auth.urls")),
)

if settings.DEBUG and not settings.PROD:
    # urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT_DEV)

dja/zap/apps/articles/models.py
import logging
from io import BytesIO

from django.core.files.uploadedfile import InMemoryUploadedFile
from django.db import models
from django.utils import timezone
from django.utils.crypto import get_random_string
from django.utils.translation import gettext_lazy as _
from PIL import Image
from tinymce.models import HTMLField
from zap.apps.users.models import User

logger = logging.getLogger(__name__)


def uploadPathFunction(instance, filename):
    return "article/images/%s" % get_random_string(8) + filename


class Author(models.Model):
    author_slug = models.CharField(max_length=255, unique=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    name_fr = models.CharField(max_length=255, blank=True)
    name_en = models.CharField(max_length=255, blank=True)
    description_fr = HTMLField(blank=True)
    description_en = HTMLField(blank=True)

    def __str__(self):
        return self.name_fr


class Article(models.Model):
    article_slug = models.CharField(max_length=255, unique=True)
    author = models.ForeignKey(Author, on_delete=models.CASCADE, null=True, blank=True)
    title_fr = models.CharField(max_length=255, blank=True)
    title_en = models.CharField(max_length=255, blank=True)
    subtitle_fr = models.CharField(max_length=255, blank=True)
    subtitle_en = models.CharField(max_length=255, blank=True)
    content_fr = HTMLField(blank=True)
    content_en = HTMLField(blank=True)
    created_at = models.DateTimeField(default=timezone.now)
    updated_at = models.DateTimeField(default=timezone.now)
    image_main = models.ImageField(upload_to=uploadPathFunction, null=True, blank=True)
    image_tumbnail = models.ImageField(
        upload_to=uploadPathFunction, null=True, blank=True
    )

    def __str__(self):
        return self.article_slug

    class Meta:
        ordering = ["-updated_at"]

    def save(self, *args, **kwargs):
        # compute a tumbnail image when article object is saved
        super().save(*args, **kwargs)
        if self.image_main:
            my_form = ImageCreationForm({}, {"image_main": self.image_main})
            if my_form.is_valid():
                self.image_tumbnail.save("thumbnail.jpg", my_form.save(), save=False)
                super().save(*args, **kwargs)
            else:
                logger.info(f"warning: Article form errors: {my_form.errors}")


class ImageContent(models.Model):
    article = models.ForeignKey(Article, on_delete=models.CASCADE)
    image = models.ImageField(upload_to=uploadPathFunction)

    def __str__(self):
        return self.image.url


from django import forms


class ImageCreationForm(forms.Form):
    # creates a image_tumbnail from image_main of 16/9 ratio centered and then rescaled to 426,240
    image_main = forms.ImageField()

    def save(self):
        image_main = self.cleaned_data["image_main"]
        img = Image.open(image_main)
        width, height = img.size
        ratio = width / height
        if ratio > 16 / 9:
            newwidth = int(height * 16 / 9)
            gap = int((width - newwidth) / 2)
            area = (gap, 0, gap + newwidth, height)
            img = img.crop(area)
        else:
            newheight = int(width * 9 / 16)
            gap = int((height - newheight) / 2)
            area = (0, gap, width, gap + newheight)
            img = img.crop(area)
        new_size = (426, 240)
        img = img.resize(new_size, Image.Resampling.LANCZOS)
        thumbnail_io = BytesIO()
        img.save(thumbnail_io, format="JPEG")
        thumbnail_file = InMemoryUploadedFile(
            thumbnail_io, None, "thumbnail.jpg", "image/jpeg", thumbnail_io.tell(), None
        )
        return thumbnail_file

dja/zap/apps/articles/forms.py
from django.core.exceptions import ValidationError
from django.forms import ModelForm

from .models import Article, Author, ImageContent


class AuthorForm(ModelForm):
    class Meta:
        model = Author
        fields = "__all__"
class ArticleForm(ModelForm):
    class Meta:
        model = Article
        fields = "__all__"
class ImageContentForm(ModelForm):
    class Meta:
        model = ImageContent
        fields = "__all__"

dja/zap/apps/articles/views.py
import time

from django.core.paginator import EmptyPage, Paginator
from django.http import HttpResponseBadRequest
from django.shortcuts import get_object_or_404, render
from django.views import View

from .models import Article, Author


class AuthorPage(View):
    def get(self, request, author_slug):
        author = get_object_or_404(Author, author_slug=author_slug)
        return render(request, "articles/author.html", {"author": author})


class ListOfArticles(View):

    def get(self, request):
        articles = Article.objects.all()
        p = Paginator(articles, 20, 2)
        page_num = int(request.GET.get("page", 1))
        if page_num > p.num_pages:
            return HttpResponseBadRequest()
        try:
            page = p.page(page_num)
        except EmptyPage:
            page = p.page(1)
        if self.request.htmx:
            return render(
                request, "articles/articles_page_htmx.html", {"articles": page}
            )
        return render(request, "articles/articles.html", {"articles": page})


class ArticlePage(View):
    def get(self, request, article_slug):
        article = get_object_or_404(Article, article_slug=article_slug)
        return render(request, "articles/article.html", {"article": article})

dja/templates/articles/article.html
{% extends 'main.html' %}
{% load i18n %} {% load l10n %} {% load tz %} {% load static %} {% load my_filters %}
{% get_current_language as LANGUAGE_CODE %}
{% block title %}{% if LANGUAGE_CODE == 'fr' %}{{ article.title_fr }}{% else %}{{ article.title_en }}{% endif %}{% endblock %}
{% block desc %}{% if LANGUAGE_CODE == 'fr' %}{{ article.subtitle_fr }}{% else %}{{ article.subtitle_en }}{% endif %}{% endblock %}
{% block jsonld %}
{% get_current_language as LANGUAGE_CODE %}
<script type="application/ld+json">
  {
    "@context": "https://schema.org",
    "@type": "NewsArticle",
    "headline": "{% if LANGUAGE_CODE == 'en' %}{{ article.title_en }}{% else %}{{ article.title_fr }}{% endif %}",
    "image": [
      "{{request.site.domain}}{{ article.article_image.url }}",
    ],
    "datePublished": "{{ article.created_at|utc|date:'Y-m-d\TH:i:s\Z' }}",
    "dateModified": "{{ article.updated_at|utc|date:'Y-m-d\TH:i:s\Z' }}",
    "author": [{
      "@type": "Person",
      "name": "{% if LANGUAGE_CODE == 'en' %}{{ article.author.name_en }}{% else %}{{ article.author.name_fr }}{% endif %}",
      "url": "{{request.site.domain}}{% url 'articles:author' article.author.author_slug %}"
    }],
    "isAccessibleForFree": "true",
  }
</script>{% endblock %}

{% block content %}
<main class="mainHFull">
  <section class="home_section article_style">
    <div class="container-fluid ">
      {% get_current_language as LANGUAGE_CODE %}

      <article>
        <p>
          {% if LANGUAGE_CODE == 'en' %}
          <h1>{{ article.title_en }}</h1>
          <h3>{{ article.subtitle_en }}</h3>
          {% else %}
          <h1>{{ article.title_fr }}</h1>
          <h3>{{ article.subtitle_fr }}</h3>
          {% endif %}
          <div class="d-flex justify-content-between align-items-center flex-wrap">
            <div class="mx-3">{% trans "By" %}
              {% if article.author.user.avatar %}
              <img src="{{ article.author.user.avatar.url }}" width="30px" alt="Avatar">
              {% else %}
              <img src="{% static '/images/icons/avatar.svg' %}" width="30px" alt="Avatar">
              {% endif %}
              <a href="{% url 'articles:author' article.author.author_slug %}">
                {% if LANGUAGE_CODE == 'en' %}
                {{ article.author.name_en }}
                {% else %}
                {{ article.author.name_fr }}
                {% endif %}
              </a>
            </div>
            <div class=" m-3 d-flex flex-wrap">
              <time> {% trans "Created: " %}:
                {{ article.created_at|date:"Y M d H:i O" }}</time>
              <time> {% if article.created_at != article.updated_at %}&nbsp&nbsp&nbsp&nbsp {% trans "updated" %}
                {{ article.updated_at|custom_time_since }}
                {% endif %}</time>
            </div>
          </div>
          <img
            src="{% if article.image_main.url is not None %} {{ article.image_main.url }} {% else %} {% static 'images/default/article_image_main.png' %} {% endif %}"
            width="600px" alt="">
        </p>
        <div>
          {% if LANGUAGE_CODE == 'en' %}
          {{ article.content_en|safe }}
          {% else %}
          {{ article.content_fr|safe }}
          {% endif %}
        </div>
      </article>

    </div>
  </section>
</main>

{% comment %} {% include 'base/footers/footer_small.html' %} {% endcomment %}
{% include 'base/footers/footer_small.html' %}

{% endblock %}

dja/templates/articles/articles.html
{% extends 'main.html' %}
{% load i18n %} {% load l10n %} {% load static %}
{% block title %}{% trans "Articles" %}{% endblock %}
{% block desc %}{% trans "" %}{% endblock %}
{% block content %}

<script src="https://unpkg.com/htmx.org@1.9.4"></script>
{% comment %} Force the scrolling to the top of the page {% endcomment %}
<script>
  history.scrollRestoration = "manual";
  window.addEventListener('beforeunload', function () {
    window.scroll(0, 0);
  });
</script>
<main class="mainHLessFooter ">
  <section class="home_section container-fluid">

    <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 row-cols-lg-4 g-2">

      {% comment %} bootstrap spinner mixed with htmx id and class {% endcomment %}
      <div id="my-indicator" class=" htmx-indicator spinner-border spinner_style" role="status">
        <span class="sr-only"></span>
      </div>

      {% include 'articles/articles_page_htmx.html' %}

    </div>
  </section>
</main>
{% comment %} {% include 'base/footers/footer_small.html' %} {% endcomment %}
{% include 'base/footers/footer_small.html' %}


{% endblock %}

dja/templates/articles/articles_page_htmx.html
{% load i18n %} {% load l10n %} {% load static %} {% load my_filters %}
{% for article in articles %}
<div class="card">
  <a href="{% url 'articles:article' article.article_slug %}">
    <img class="card-img-top"
      src="{% if article.image_tumbnail.url is not None %} {{ article.image_tumbnail.url }} {% else %} {% static 'images/default/article_image_thumbnail.png' %} {% endif %}"
      alt="Card image cap" style="">
    <div class="card-body">
      {% get_current_language as LANGUAGE_CODE %}
      {% if LANGUAGE_CODE == 'en' %}
      <h5 class="card-title">{{ article.title_en }}</h5>
      <h6 class="card-text">{{ article.subtitle_en }}</h6>
      {% else %}
      <h5 class="card-title">{{ article.title_fr }}</h5>
      <h6 class="card-text">{{ article.subtitle_fr }}</h6>
      {% endif %}
      <div class="card-text">{{ article.updated_at|custom_time_since|capfirst }}</div>
    </div>
  </a>
</div>
{% endfor %}
<div hx-trigger="intersect once" hx-get="{% url 'articles:articles' %}?page={{ articles.number|add:1 }}"
  hx-swap="outerHTML" hx-indicator="#my-indicator">&nbsp;
</div>

dja/templates/articles/author.html
{% extends 'main.html' %}
{% load i18n %} {% load l10n %} {% load tz %} {% load static %}
{% get_current_language as LANGUAGE_CODE %}
{% block title %}{% if LANGUAGE_CODE == 'fr' %}{{ author.name_fr }}{% else %}{{ author.name_en }}{% endif %}{% endblock %}
{% block content %}


<main class="d-flex flex-fill">
  <section class="m-0 p-0 article_style">
    <div class="container-fluid m-0 p-0">
      {% get_current_language as LANGUAGE_CODE %}
      {% if LANGUAGE_CODE == 'en' %}

      {% else %}

      {% endif %}
    </div>
  </section>
</main>

{% comment %} {% include 'base/footers/footer_small.html' %} {% endcomment %}
{% include 'base/footers/footer_small.html' %}

{% endblock %}